name: 1 - Publish to npm
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Create auth file
        run: |
          cp ./.npmrc.sample ./.npmrc
          sed -i 's/$GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .npmrc
          cat .npmrc
      - name: Install project dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - run: git config user.email "faraway@faraway.com"
      - run: git config user.name "@github-ci"
      - name: Publish
        run: yarn publish

